// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3D-GyXJMgoQqkSQbKlkVTXQKRDSLWdXA',
    appId: '1:1032477154617:web:994cba7429e2aff5e79ce8',
    messagingSenderId: '1032477154617',
    projectId: 'borrow-26a99',
    authDomain: 'borrow-26a99.firebaseapp.com',
    storageBucket: 'borrow-26a99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbztUUiZrypaatfDVpx1cccUVmFWqiBGY',
    appId: '1:1032477154617:android:77f50ed21f0be1d8e79ce8',
    messagingSenderId: '1032477154617',
    projectId: 'borrow-26a99',
    storageBucket: 'borrow-26a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcsZJESYDqWaBiSM9IYSGsme6g3py71pg',
    appId: '1:1032477154617:ios:b547c8a4c8c747a7e79ce8',
    messagingSenderId: '1032477154617',
    projectId: 'borrow-26a99',
    storageBucket: 'borrow-26a99.appspot.com',
    iosClientId: '1032477154617-1tb4uo1l4kgj2n5ll8ndp43e8d06rt74.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcsZJESYDqWaBiSM9IYSGsme6g3py71pg',
    appId: '1:1032477154617:ios:8e038cd94156264de79ce8',
    messagingSenderId: '1032477154617',
    projectId: 'borrow-26a99',
    storageBucket: 'borrow-26a99.appspot.com',
    iosClientId: '1032477154617-n5qkl7rbep4qf9rsmcr4p4ppbdqhdf6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrow.RunnerTests',
  );
}
